# The migrations database to record migration logging and tracking
# This can have the same connection details as the Wynncraft database
MIGRATIONS_DATABASE_ADDRESS: "localhost"
MIGRATIONS_DATABASE_PORT: "5432"
MIGRATIONS_DATABASE_USERNAME: "root"
MIGRATIONS_DATABASE_PASSWORD: "wynncraft"
MIGRATIONS_DATABASE_NAME: "migrations"
MIGRATIONS_DATABASE_DISPLAY_NAME: "Migrations"

# Hosts the tables that store all user data and data needed for the plugin to persist
# This CAN be used for migrations, but it is recommended not to for a production server
WYNNCRAFT_DATABASE_ADDRESS: "localhost"
WYNNCRAFT_DATABASE_PORT: "5432"
WYNNCRAFT_DATABASE_USERNAME: "root"
WYNNCRAFT_DATABASE_PASSWORD: "wynncraft"
WYNNCRAFT_DATABASE_NAME: "wynncraft"
WYNNCRAFT_DATABASE_DISPLAY_NAME: "Wynncraft Core"

# The InfluxDB instance that the plugin should use to store data
# Connection details are provided here, but are specified in the Docker Compose
# ORG and BUCKET are NOT to be relied upon during connection
WYNNCRAFT_INFLUX_ADDRESS: "localhost"
WYNNCRAFT_INFLUX_PORT: 8086
WYNNCRAFT_INFLUX_TOKEN: 'Dv96E;3Vumr7u_+88£xK(5MO;?N,(6U?h-k"$KL;@u,#;6plFR'
WYNNCRAFT_INFLUX_DEFAULT_ORG: "wynncraft"
WYNNCRAFT_INFLUX_DEFAULT_BUCKET: "wynncraft"

# Resource pack file details to apply to all players
WYNNCRAFT_RESOURCE_ACTIVE_PACK_TYPE: "PRODUCTION" # PRODUCTION or DEVELOPMENT
WYNNCRAFT_RESOURCE_ACTIVE_PACK_ID: "000000000000000000000000000000000000" # ID of resource pack stored in CDN
WYNNCRAFT_RESOURCE_PACK_UUID: "00000000-0000-0000-0000-000000000000" # UUID of resource pack itself, this can be random but must change when the pack changes

# The context, or URI that the resource pack is hosted under in the CDN
WYNNCRAFT_CDN_ENABLE: TRUE
WYNNCRAFT_RESOURCE_PACK_FALLBACK: "https://wynncraft.com/"
WYNNCRAFT_RESOURCE_PACK_CONTEXT: "/resource-pack/"
WYNNCRAFT_CDN_SERVER_SSL: FALSE # True determines usage of https, false determines usage of http
WYNNCRAFT_CDN_SERVER_HOST: "localhost"
WYNNCRAFT_CDN_SERVER_PORT: 2873
WYNNCRAFT_FORCE_RESOURCE_PACK: FALSE

# Instancing and world configuration
WYNNCRAFT_MAIN_WORLD: "wynncraft"
WYNNCRAFT_MAIN_COORDINATES: "-882,67,-1576"
WYNNCRAFT_LIMBO_WORLD: "limbo"
WYNNCRAFT_LIMBO_COORDINATES: "0,0,0" # X, Y, Z
WYNNCRAFT_LOBBY_WORLD: "lobby"
WYNNCRAFT_LOBBY_COORDINATES: "0,0,0" # X, Y, Z

WYNNCRAFT_SERVER_INSTANCE_ID: "WA3" # The ID of the server instance that this plugin is running on. This should vary between servers

# Development mode; Determines whether development features should be enabled for the instance
DEVELOPMENT_MODE: FALSE