# The migrations database to record migration logging and tracking
# This can have the same connection details as the Wynncraft database
MIGRATIONS_DATABASE_ADDRESS: "localhost"
MIGRATIONS_DATABASE_PORT: "5432"
MIGRATIONS_DATABASE_USERNAME: "root"
MIGRATIONS_DATABASE_PASSWORD: "wynncraft"
MIGRATIONS_DATABASE_NAME: "migrations"
MIGRATIONS_DATABASE_DISPLAY_NAME: "Migrations"

# Hosts the tables that store all user data and data needed for the plugin to persist
# This CAN be used for migrations, but it is recommended not to for a production server
WYNNCRAFT_DATABASE_ADDRESS: "localhost"
WYNNCRAFT_DATABASE_PORT: "5432"
WYNNCRAFT_DATABASE_USERNAME: "root"
WYNNCRAFT_DATABASE_PASSWORD: "wynncraft"
WYNNCRAFT_DATABASE_NAME: "wynncraft"
WYNNCRAFT_DATABASE_DISPLAY_NAME: "Wynncraft Core"

# The InfluxDB instance that the plugin should use to store data
# Connection details are provided here, but are specified in the Docker Compose
# ORG and BUCKET are NOT to be relied upon during connection
WYNNCRAFT_INFLUX_ADDRESS: "localhost"
WYNNCRAFT_INFLUX_PORT: 8086
WYNNCRAFT_INFLUX_TOKEN: 'Dv96E;3Vumr7u_+88£xK(5MO;?N,(6U?h-k"$KL;@u,#;6plFR'
WYNNCRAFT_INFLUX_ORG: "wynncraft"
WYNNCRAFT_INFLUX_BUCKET: "wynncraft"

# The ID of the server instance that this plugin is running on. This should vary between servers
WYNNCRAFT_SERVER_INSTANCE_ID: "WA3"

# Development mode; Determines whether development features should be enabled for the instance
DEVELOPMENT_MODE: FALSE