name: Build CI with multiple platforms/configs

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ubunutu-jdk21:
    name: 'Ubuntu Latest (JDK ${{ vars.JAVA_VERSION }})'
    runs-on: ubuntu-latest
    environment: jdk21-building
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK ${{ vars.JAVA_VERSION }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ vars.JAVA_VERSION }}
        distribution: ${{ vars.UBUNTU_DISTRIBUTION }}

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

    - name: Build with Gradle Wrapper
      run: ./gradlew build --scan

  macos-jdk21:
    name: 'MacOS Latest (JDK ${{ vars.JAVA_VERSION }})'
    runs-on: macos-latest
    environment: jdk21-building
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK ${{ vars.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ vars.JAVA_VERSION }}
          distribution: ${{ vars.MACOS_DISTRIBUTION }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

      - name: Build with Gradle Wrapper
        run: ./gradlew build --scan

  windows-jdk21:
    name: 'Windows Latest (JDK ${{ vars.JAVA_VERSION }})'
    runs-on: windows-latest
    environment: jdk21-building
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK ${{ vars.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: ${{ vars.WINDOWS_DISTRIBUTION }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

      - name: Build with Gradle Wrapper
        run: ./gradlew build --scan