name: Publish Changelog

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  version:
    if: ${{ startsWith(github.event.head_commit.message, 'feat') }}
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - uses: actions/checkout@v2
      - uses: thecodemonkey/action-get-gradle-version@master
        id: version
      - run: 'echo version ${{ steps.version.outputs.version }}'

  release:
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.event.head_commit.message, 'feat') }}
    needs: version

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - run: echo "previous_tag=$(git describe --tags --abbrev=0 2>/dev/null || echo '')" >> $GITHUB_ENV
      - name: Generate changelog
        id: changelog
        uses: jaywcjlove/changelog-generator@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filter: '[R|r]elease[d]\s+[v|V]\d(\.\d+){0,2}'

      - name: Get the changelog
        run: echo "${{ steps.changelog.outputs.changelog }}"

      - name: Create github release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{needs.version.outputs.version}}
          release_name: ${{needs.version.outputs.version}}
          body: |
            Grab the new version from https://github.com/IanTapply22/Wynncraft/packages/2160010 version ${{needs.version.outputs.version}}
            
            ```
            <dependencies>
            	<dependency>
            	    <groupId>com.iantapply</groupId>
            	    <artifactId>wynncraft</artifactId>
            	    <version>${{needs.version.outputs.version}}</version>
            	</dependency>
            </dependencies>
            ```
            ### Changelog
            ${{ steps.changelog.outputs.changelog }}
          draft: false
          prerelease: false
