name: Publish Package to GitHub Packages

on:
  push:
    branches: [ "main" ]

jobs:
  version:
    name: Fetch Gradle Version
    if: ${{ startsWith(github.event.head_commit.message, 'feat') }}
    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.version.outputs.version }}

    steps:
      - uses: actions/checkout@v2
      - uses: thecodemonkey/action-get-gradle-version@master
        id: version
      - run: 'echo version ${{ steps.version.outputs.version }}'

  publish:
    name: Publish Package
    if: ${{ startsWith(github.event.head_commit.message, 'feat') }}
    needs: version
    runs-on: ubuntu-latest
    environment: jdk21-publishing
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: ${{ vars.JAVA_VERSION }}
          distribution: ${{ vars.JAVA_DISTRIBUTION }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

      - name: Publish package
        run: ./gradlew publish
        env:
          GITHUB_USERNAME: ${{ secrets.GITHUB_ACTOR }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}